In [11]:
from huggingface_hub import notebook_login

notebook_login()

In [30]:
from sentence_transformers import SentenceTransformer
from transformers import AutoConfig
st_model_path = "output/official/contrastive/crosslingual/20241031-185451"
# hf_model_path = "UPC-HLE/fc-crosslingual-jina-reranker-v2-base-multilingual"
hf_model_path = "UPC-HLE/cross-example2"
model_st= SentenceTransformer(model_name_or_path=st_model_path, trust_remote_code=True)
config = AutoConfig.from_pretrained(st_model_path, trust_remote_code=True)

No sentence-transformers model found with name output/official/contrastive/crosslingual/20241031-185451. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at output/official/contrastive/crosslingual/20241031-185451 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [37]:
from huggingface_hub import HfApi
api = HfApi()

api.create_repo(hf_model_path, exist_ok=True, private=True)
api.upload_folder(
    folder_path=st_model_path,
    repo_id=hf_model_path,
    repo_type="model",
    commit_message="Initial commit",
)

No files have been modified since last commit. Skipping to prevent empty commit.


CommitInfo(commit_url='https://huggingface.co/UPC-HLE/cross-example2/commit/765bcce3cf0bfcddcd70ab3741a7bb3eccd19d0b', commit_message='Initial commit', commit_description='', oid='765bcce3cf0bfcddcd70ab3741a7bb3eccd19d0b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/UPC-HLE/cross-example2', endpoint='https://huggingface.co', repo_type='model', repo_id='UPC-HLE/cross-example2'), pr_revision=None, pr_num=None)

In [ ]:
# model_st.push_to_hub(hf_model_path, private=True, exist_ok=True)
# config.push_to_hub(hf_model_path, private=True, exist_ok=True)

CommitInfo(commit_url='https://huggingface.co/UPC-HLE/fc-crosslingual-jina-reranker-v2-base-multilingual/commit/7765f6e534a5d0ee6b97ca9e1ec26d4e0f4e231b', commit_message='Upload config', commit_description='', oid='7765f6e534a5d0ee6b97ca9e1ec26d4e0f4e231b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/UPC-HLE/fc-crosslingual-jina-reranker-v2-base-multilingual', endpoint='https://huggingface.co', repo_type='model', repo_id='UPC-HLE/fc-crosslingual-jina-reranker-v2-base-multilingual'), pr_revision=None, pr_num=None)

In [35]:
from transformers import AutoModelForSequenceClassification, AutoConfig

# # hf_model_path = "UPC-HLE/cross-example"
# config = AutoConfig.from_pretrained(
#     hf_model_path,
#     trust_remote_code=True,
# )

# model = AutoModelForSequenceClassification.from_pretrained(
#     hf_model_path,
#     torch_dtype="auto",
#     trust_remote_code=True,
#     config=config,
# ).to('cuda').eval()

st0 = SentenceTransformer(st_model_path, trust_remote_code=True)
st1 = SentenceTransformer(hf_model_path, trust_remote_code=True)

print(st0.similarity(st0.encode("Hello world"), st0.encode("Hello world")))
print(st1.similarity(st0.encode("Hello world"), st1.encode("Hello world")))

No sentence-transformers model found with name output/official/contrastive/crosslingual/20241031-185451. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at output/official/contrastive/crosslingual/20241031-185451 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No sentence-transformers model found with name UPC-HLE/cross-example2. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at UPC-HLE/cross-example2 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

tensor([[1.0000]])
tensor([[1.0000]])


In [34]:
st0 = SentenceTransformer(st_model_path, trust_remote_code=True)
st0

No sentence-transformers model found with name output/official/contrastive/crosslingual/20241031-185451. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at output/official/contrastive/crosslingual/20241031-185451 and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


SentenceTransformer(
  (0): Transformer({'max_seq_length': 1024, 'do_lower_case': False}) with Transformer model: XLMRobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [24]:
from sentence_transformers import SentenceTransformer

# Download from the 🤗 Hub
model = SentenceTransformer("UPC-HLE/cross-example", trust_remote_code=True)
# Run inference
sentences = [
    'The weather is lovely today.',
    "It's so sunny outside!",
    'He drove to the stadium.',
]
embeddings = model.encode(sentences)
print(embeddings.shape)
# [3, 768]

# Get the similarity scores for the embeddings
similarities = model.similarity(embeddings, embeddings)
print(similarities.shape)
# [3, 3]


No sentence-transformers model found with name UPC-HLE/cross-example. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at UPC-HLE/cross-example and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


(3, 768)
torch.Size([3, 3])


In [17]:
st = SentenceTransformer("UPC-HLE/cross-example", trust_remote_code=True)
st

No sentence-transformers model found with name UPC-HLE/cross-example. Creating a new one with mean pooling.
Some weights of XLMRobertaModel were not initialized from the model checkpoint at UPC-HLE/cross-example and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 1024, 'do_lower_case': False}) with Transformer model: XLMRobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [27]:
s1 = "Be care ful with the Police agents paid by Trump"
s2 = "Trump paid the Police agents"

emb1 = st.encode(s1, convert_to_tensor=True)
emb2 = st.encode(s2, convert_to_tensor=True)

similarities = st.similarity(emb1, emb2)
similarities

tensor([[0.9805]], device='cuda:0', dtype=torch.bfloat16)

In [28]:
s1 = "Be care ful with the Police agents paid by Trump"
s2 = "Trump paid the Police agents"

emb1 = st0.encode(s1, convert_to_tensor=True)
emb2 = st0.encode(s2, convert_to_tensor=True)

similarities = st0.similarity(emb1, emb2)
similarities

tensor([[0.9805]], device='cuda:0', dtype=torch.bfloat16)

In [4]:
from transformers import AutoModelForSequenceClassification, AutoConfig

model = AutoModelForSequenceClassification.from_pretrained(
    hf_model_path,
    torch_dtype="auto",
    trust_remote_code=True,
).to('cuda').eval()

config = AutoConfig.from_pretrained(
    hf_model_path,
    trust_remote_code=True,
)

candidates = ["the car goes fast", "the car goes slow", "the bicycle goes slow"]
sentence_pairs = [["the car drives fast", doc] for doc in candidates]

scores = model.compute_score(sentence_pairs, max_length=1024)
print(scores)

# model.push_to_hub("UPC-HLE/example2", private=True, exist_ok=True)
# config.push_to_hub("UPC-HLE/example2", private=True, exist_ok=True)

config.json:   0%|          | 0.00/1.41k [00:00<?, ?B/s]

configuration_xlm_roberta.py:   0%|          | 0.00/2.73k [00:00<?, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/UPC-HLE/fc-crosslingual-jina-reranker-v2-base-multilingual:
- configuration_xlm_roberta.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers_modules.jinaai.jina-reranker-v2-base-multilingual.126747772a932960028d9f4dc93bd5d9c4869be4.configuration_xlm_roberta.XLMRobertaFlashConfig'> and you passed <class 'transformers_modules.UPC-HLE.fc-crosslingual-jina-reranker-v2-base-multilingual.d0c6c92a69bfd036a896dacb99b9c62fd328997e.configuration_xlm_roberta.XLMRobertaFlashConfig'>. Fix one of those so they match!